### ISSUE TITLE
Overdrive button opening song menu; up strum opening quest menu

### ISSUE THREAD

**Issue by Justusis0nline** [InvoxiPlayGames/FestivalInstrumentMapper#35] opened 2024-04-28 04:42 UTC
so when i press select to use overdrive it will also open the song menu, not sure if this is mean to happen or not

**Comment by TheNathannator** [comment] 2024-04-28 05:37
This is a Fortnite issue as far as I know, but we could potentially remap it to avoid the issue (I believe left d-pad activates as well).

**Comment by AgentTrueyBluey** [comment] 2024-04-28 07:50
This may be a similar issue, but when I strum up, it opens the quest menu during songs. I haven't found a proper rebind to fix this issue, so I have to strum down for the time being.

**Comment by CarbyDood** [comment] 2024-04-28 08:19
i have the same issue with select on my GH5 wii tar pulling up the song menu, i think that's just a hard coded thing for FnF. i have not however had the issue with strum up bringing up the quest menu. Also Nathan, Wii tars don't have d-pad, they a nun chuck style analouge stick that i don't think is picked up by the mapper atm.

**Comment by Justusis0nline** [comment] 2024-04-28 09:05
update: the select button no longer activates overdrive, right now i have no way of activating it

**Comment by Jobo789** [comment] 2024-04-28 11:14
I **was** having the issue of Overdrive also opening the song menu/quests menu, as well as the strum up opening the emote wheel. Even removing the binds didn't work.

Then I closed Fortnite, re-ran the mapping tool, closed it, relaunched Fortnite and then removed all controller bindings related to the Select Button and the Down-Dpad inputs. No more overlapping inputs.

**Comment by AgentTrueyBluey** [comment] 2024-04-28 12:59
Jobo, you genius. The strum bar is considered like a d-pad. The solution appears to be to remove the controls related to the emote menu and opening the map. Find the controller settings and change those to controls that won't interfere with strumming up and down. In theory, the problem is solved.

**Comment by TheNathannator** [comment] 2024-04-28 22:40
Pinning since a solution is provided here; closing since this issue isn't on our end.

**Closed by TheNathannator** 2024-04-28 22:40 UTC
