### ISSUE TITLE
Upstrum opens exit to backstage menu

### ISSUE THREAD

**Issue by GrayHefe** [InvoxiPlayGames/FestivalInstrumentMapper#37] opened 2024-04-28 04:46 UTC
I have tried setting up several guitars. PS3 TBRB Hofner, PS3 GHWT, PS4 Strat, and a Wii GH3 Guitar through Wiitarthing. None of them work in festival but they do in the lobby menu, but can only move down once

**Comment by Justusis0nline** [comment] 2024-04-28 04:50
is the mapper recognizing them?

**Comment by GrayHefe** [comment] 2024-04-28 04:55
Yes, it says they are mapped but they won't work

**Comment by sanjay900** [comment] 2024-04-28 04:57
Make sure "disable controller inputs" is off

**Comment by Justusis0nline** [comment] 2024-04-28 04:57
go into your fortnite settings and make sure "ignore controller input is turned off"

**Comment by GrayHefe** [comment] 2024-04-28 04:58
I tried looking for it but can't find it

**Comment by Justusis0nline** [comment] 2024-04-28 05:10
it should be the 4th setting down under mouse and keyboard

**Comment by GrayHefe** [comment] 2024-04-28 05:20
It works, but my upstrum opens the exit to backstage menu

**Comment by GrayHefe** [comment] 2024-04-28 05:45
I haven't been able to fix my upstrum

**Comment by Ohern018** [comment] 2024-04-28 13:25
Experiencing the same problem with my xplorer. Upstream during the song opens "exit to backstage menu".  I've ticked the 360 controller hiding, replugged guitar after refreshing, restarted both game and computer. No luck appreciate any help.

**Comment by GrayHefe** [comment] 2024-04-28 19:22
Were you able to fix it?

**Comment by TheNathannator** [comment] 2024-04-28 22:53
Closing this as a duplicate of #35, refer to the solution there.

**Closed by TheNathannator** 2024-04-28 22:53 UTC
